version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: docker/php/DockerFile
    container_name: teste_api-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./application:/var/www/application
    environment:
      - COMPOSER_HOME=/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=local
      - APP_KEY=base64:wS2HoDJ7ib7TUklEfHus0Z4hzroWKwqt1DKJ3DcmzxQ=
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: teste_api-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./application:/var/www/application
      - ./docker/nginx:/etc/nginx/conf.d

  redis:
    build:
      context: ./
      dockerfile: docker/redis/DockerFile
    container_name: teste_api-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  db:
    build:
      context: ./
      dockerfile: docker/db/DockerFile
    container_name: teste_api-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  redis:
  db:
